#!/usr/bin/env python3
"""Generate source/main-glfw.cpp from source/main.cpp by replacing SDL3 with GLFW.

The two tutorial variants differ only in windowing, input, timing and the surface.
Keeping the GLFW file generated rather than hand-maintained means the two cannot
drift apart: after changing main.cpp (or pulling from upstream), re-run this and
let version control show whether the GLFW variant needs re-committing.

    python tools/make-glfw-variant.py            # write source/main-glfw.cpp
    python tools/make-glfw-variant.py --check    # fail if it is out of date

Every anchor below is plain ASCII C++ code, so translating or re-wording the
comments in main.cpp does not affect this script.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "source" / "main.cpp"
DST = ROOT / "source" / "main-glfw.cpp"

BANNER = """
// GLFW variant of main.cpp, generated by tools/make-glfw-variant.py.
// Only windowing, input, timing and the surface differ; see sdl-glfw-diff.md.
"""

# Input state and the four GLFW callbacks, inserted just above main().
CALLBACKS = """
// GLFW reports input through callbacks instead of a polled event queue, so the
// per-frame input is accumulated here and consumed once per frame in the render loop.
glm::vec2 mouseDelta{};      // cursor movement while the left button is held
float scrollDelta{ 0.0f };   // mouse wheel movement
glm::vec2 lastMousePos{};
bool firstMousePos{ true };

// SDL hands out relative mouse motion, GLFW only absolute positions - so keep the previous one
static void cursorPosCallback(GLFWwindow* window, double x, double y) {
\tglm::vec2 pos{ static_cast<float>(x), static_cast<float>(y) };
\tif (firstMousePos) {
\t\tlastMousePos = pos;
\t\tfirstMousePos = false;
\t}
\tconst glm::vec2 delta{ pos - lastMousePos };
\tlastMousePos = pos;
\tif (glfwGetMouseButton(window, GLFW_MOUSE_BUTTON_LEFT) == GLFW_PRESS) {
\t\tmouseDelta += delta;
\t}
}

static void scrollCallback(GLFWwindow* window, double xoffset, double yoffset) {
\tscrollDelta += static_cast<float>(yoffset);
}

static void keyCallback(GLFWwindow* window, int key, int scancode, int action, int mods) {
\tif (action != GLFW_PRESS) {
\t\treturn;
\t}
\tif (key == GLFW_KEY_KP_ADD || key == GLFW_KEY_EQUAL) {
\t\tshaderData.selected = (shaderData.selected < 2) ? shaderData.selected + 1 : 0;
\t}
\tif (key == GLFW_KEY_KP_SUBTRACT || key == GLFW_KEY_MINUS) {
\t\tshaderData.selected = (shaderData.selected > 0) ? shaderData.selected - 1 : 2;
\t}
}

static void framebufferSizeCallback(GLFWwindow* window, int width, int height) {
\tupdateSwapchain = true;
}

"""

OLD_EVENTS = """\t  // e) Event polling
\t\tfloat elapsedTime{ (SDL_GetTicks() - lastTime) / 1000.0f };
\t\tlastTime = SDL_GetTicks();
\t\tfor (SDL_Event event; SDL_PollEvent(&event);) {
\t\t\tif (event.type == SDL_EVENT_QUIT) {
\t\t\t\tquit = true;
\t\t\t\tbreak;
\t\t\t}
\t\t\tif (event.type == SDL_EVENT_MOUSE_MOTION) {
\t\t\t\tif (event.button.button == SDL_BUTTON_LEFT) {
\t\t\t\t\tobjectRotations[shaderData.selected].x -= (float)event.motion.yrel * elapsedTime;
\t\t\t\t\tobjectRotations[shaderData.selected].y += (float)event.motion.xrel * elapsedTime;
\t\t\t\t}
\t\t\t}
\t\t\tif (event.type == SDL_EVENT_MOUSE_WHEEL) {
\t\t\t\tcamPos.z += (float)event.wheel.y * elapsedTime * 10.0f;
\t\t\t}
\t\t\tif (event.type == SDL_EVENT_KEY_DOWN) {
\t\t\t\tif (event.key.key == SDLK_PLUS || event.key.key == SDLK_KP_PLUS) {
\t\t\t\t\tshaderData.selected = (shaderData.selected < 2) ? shaderData.selected + 1 : 0;
\t\t\t\t}
\t\t\t\tif (event.key.key == SDLK_MINUS || event.key.key == SDLK_KP_MINUS) {
\t\t\t\t\tshaderData.selected = (shaderData.selected > 0) ? shaderData.selected - 1 : 2;
\t\t\t\t}
\t\t\t}
"""

NEW_EVENTS = """\t  // e) Event polling
\t\tfloat elapsedTime{ static_cast<float>(glfwGetTime() - lastTime) };
\t\tlastTime = glfwGetTime();
\t\t// reset the accumulators, glfwPollEvents runs the callbacks that fill them,
\t\t// f) Window resize is handled by framebufferSizeCallback
\t\tmouseDelta = glm::vec2(0.0f);
\t\tscrollDelta = 0.0f;
\t\tglfwPollEvents();
\t\tif (glfwWindowShouldClose(window)) {
\t\t\tquit = true;
\t\t}
\t\tobjectRotations[shaderData.selected].x -= mouseDelta.y * elapsedTime;
\t\tobjectRotations[shaderData.selected].y += mouseDelta.x * elapsedTime;
\t\tcamPos.z += scrollDelta * elapsedTime * 10.0f;
"""

# The tail of the SDL event loop: the resize case plus the closing brace of the
# poll loop. GLFW handles resize in a callback, so both disappear.
OLD_RESIZE = """
\t\t  // f) Window resize
\t\t\tif (event.type == SDL_EVENT_WINDOW_RESIZED) {
\t\t\t\tupdateSwapchain = true;
\t\t\t}
\t\t}
"""

# (old, new) applied in order; each must match exactly once.
EDITS = [
    # --- headers ---
    ("#include <SDL3/SDL.h>\n#include <SDL3/SDL_vulkan.h>\n",
     "#define GLFW_INCLUDE_NONE\n#include <GLFW/glfw3.h>\n"),
    # SDL pulled in <assert.h> transitively, GLFW does not
    ("#include <iostream>\n#include <filesystem>\n",
     "#include <iostream>\n#include <filesystem>\n#include <cassert>\n"),
    # --- input state and callbacks, just above main() ---
    ("// huge main\nint main(", CALLBACKS + "// huge main\nint main("),
    # --- init: GLFW loads the Vulkan loader itself, on demand ---
    ("\tchk(SDL_Init(SDL_INIT_VIDEO));\n\tchk(SDL_Vulkan_LoadLibrary(NULL));\n",
     "\tchk(glfwInit());  // GLFW loads the Vulkan loader itself, on demand\n"),
    # --- instance extensions ---
    ("SDL_Vulkan_GetInstanceExtensions(&instanceExtensionsCount)",
     "glfwGetRequiredInstanceExtensions(&instanceExtensionsCount)"),
    # --- presentation support ---
    ("chk(SDL_Vulkan_GetPresentationSupport(instance, devices[deviceIndex], queueFamily));",
     "chk(glfwGetPhysicalDevicePresentationSupport(instance, devices[deviceIndex], queueFamily));"),
    # --- window, surface and callback registration ---
    ("\tSDL_Window* window = SDL_CreateWindow(\"How to Vulkan\", 1280u, 720u, "
     "SDL_WINDOW_VULKAN | SDL_WINDOW_RESIZABLE);\n"
     "\tassert(window);\n"
     "\tchk(SDL_Vulkan_CreateSurface(window, instance, nullptr, &surface));\n"
     "\tchk(SDL_GetWindowSize(window, &windowSize.x, &windowSize.y));\n",
     "\tglfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);  // no OpenGL context, this is a Vulkan window\n"
     "\tglfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);\n"
     "\tGLFWwindow* window = glfwCreateWindow(1280, 720, \"How to Vulkan\", nullptr, nullptr);\n"
     "\tassert(window);\n"
     "\tchk(glfwCreateWindowSurface(instance, window, nullptr, &surface));\n"
     "\tglfwGetFramebufferSize(window, &windowSize.x, &windowSize.y);\n"
     "\tglfwSetCursorPosCallback(window, cursorPosCallback);\n"
     "\tglfwSetScrollCallback(window, scrollCallback);\n"
     "\tglfwSetKeyCallback(window, keyCallback);\n"
     "\tglfwSetFramebufferSizeCallback(window, framebufferSizeCallback);\n"),
    # --- frame timing: GLFW counts seconds, SDL_GetTicks counted milliseconds ---
    ("\tuint64_t lastTime{ SDL_GetTicks() };",
     "\tdouble lastTime{ glfwGetTime() };  // GLFW counts seconds, SDL_GetTicks counted milliseconds"),
    # --- event handling ---
    (OLD_EVENTS, NEW_EVENTS),
    (OLD_RESIZE, ""),
    # --- swapchain recreation asks for the framebuffer size, not the window size ---
    ("\t\t\tchk(SDL_GetWindowSize(window, &windowSize.x, &windowSize.y));",
     "\t\t\tglfwGetFramebufferSize(window, &windowSize.x, &windowSize.y);"),
    # --- teardown: no subsystem to quit separately ---
    ("\tSDL_DestroyWindow(window);\n\tSDL_QuitSubSystem(SDL_INIT_VIDEO);\n\tSDL_Quit();\n",
     "\tglfwDestroyWindow(window);\n\tglfwTerminate();\n"),
]


def generate(text):
    """Apply every edit to the SDL source text and return the GLFW variant."""
    for old, new in EDITS:
        found = text.count(old)
        if found != 1:
            raise SystemExit(
                "anchor matched %d times, expected exactly 1:\n%r" % (found, old[:160]))
        text = text.replace(old, new)

    # banner goes after the license header, before the first #define
    marker = "\n#define VOLK_IMPLEMENTATION"
    if text.count(marker) != 1:
        raise SystemExit("could not place the banner: VOLK_IMPLEMENTATION marker not unique")
    text = text.replace(marker, BANNER + marker, 1)

    # the word SDL may survive in explanatory comments, but never in code
    code = "\n".join(line.split("//")[0] for line in text.split("\n"))
    leftovers = [l.strip() for l in code.split("\n") if "SDL" in l]
    if leftovers:
        raise SystemExit("SDL still referenced in code: %r" % leftovers)
    return text


def main():
    check = "--check" in sys.argv
    # read as bytes and normalise, so CRLF endings survive the round trip
    raw = SRC.read_bytes().decode("utf-8")
    crlf = "\r\n" in raw
    result = generate(raw.replace("\r\n", "\n"))
    if crlf:
        result = result.replace("\n", "\r\n")
    out = result.encode("utf-8")

    if check:
        current = DST.read_bytes() if DST.exists() else b""
        if current != out:
            raise SystemExit(
                "%s is out of date - re-run: python tools/make-glfw-variant.py" % DST.name)
        print("%s is up to date" % DST.name)
        return
    DST.write_bytes(out)
    print("wrote %s (%d bytes)" % (DST.name, len(out)))


if __name__ == "__main__":
    main()
